name: Publish container image

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_image:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: hermitcore
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/hermit-os/test:latest
